apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-graphy
  namespace: insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight-graphy
      version: "1.0"
  template:
    metadata:
      labels:
        app: insight-graphy
        version: "1.0"
    spec:
      containers:
      - name: graphy-app
        image: magnarox/graphy:1.0.0
        imagePullPolicy: Always
        env:
         - name: VERTEX_THRESHOLD
           value: '4'
         - name: SERVER_PORT
           value: "8080"  
         - name: JAVA_OPTS
           value: " -Xms256m -Xmx2048m"
         - name: ENDPOINT
           value: "insight-janusgraph"
         - name: PORT
           value: "8182"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "2200Mi"
            cpu: "1"
        ports:
        - name: graphy
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: insight-graphy
  namespace: insight
spec:
  selector:
    app: insight-graphy
  type: NodePort
  ports:
  - name: graphy
    port: 8080
    nodePort: 30200 
    targetPort: 8080